# Generated by Django 6.0.5 on 2026-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Icon',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
