# Generated by Django 6.0.5 on 2026-06-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_game_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Icon',
            field=models.ImageField(default='static/img/RE2.png', upload_to=''),
        ),
    ]
