# Generated by Django 6.0.5 on 2026-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_game_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Icon',
            field=models.ImageField(default='Unknown', null=True, upload_to=''),
        ),
    ]
