# Generated by Django 6.0.5 on 2026-06-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_alter_game_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Icon',
            field=models.ImageField(blank=True, default='Unknown', null=True, upload_to='IMG/'),
        ),
    ]
