# Generated by Django 6.0.5 on 2026-06-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_alter_game_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Creator',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='Discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='Platforms',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
