# Generated by Django 6.0.5 on 2026-06-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_game_creator_game_discount_game_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Subscription',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
