# Generated by Django 6.0.5 on 2026-06-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_game_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Name',
            field=models.CharField(max_length=1000),
        ),
    ]
