# Generated by Django 6.0.5 on 2026-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Rating', models.FloatField()),
                ('Creator', models.CharField(blank=True, default='Unknown', max_length=150, null=True)),
                ('Icon', models.CharField(blank=True, default='Unknown', null=True)),
            ],
        ),
    ]
