# Generated by Django 6.0.5 on 2026-09-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_client', '0002_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
