# Generated by Django 6.0.5 on 2026-09-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_client', '0003_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
